### ISSUE TITLE
As a user, I want the view to be optimized for tablets

### ISSUE THREAD

**Issue by madasamys** [mcruncher/worshipsongs-ios#119]
In order to fully utilize the space.
As a user, I want the view to be optimized for tablets.

**Comment by michelleashwini** [comment]
![list-of-songs](https://cloud.githubusercontent.com/assets/15209503/23789399/a3df9b10-05b5-11e7-840c-6a809c930480.png)
![selected song](https://cloud.githubusercontent.com/assets/15209503/23789400/a3e2b94e-05b5-11e7-84a9-749a9898ae0c.png)
![songs-dropdown](https://cloud.githubusercontent.com/assets/15209503/23789401/a3e94584-05b5-11e7-94f3-bcd4143f48b3.png)
![artist-dropdown](https://cloud.githubusercontent.com/assets/15209503/23789418/b24a96a0-05b5-11e7-8cce-88950343b756.png)
![artist-song-dropdown2](https://cloud.githubusercontent.com/assets/15209503/23789436/c5803342-05b5-11e7-86d6-88906cb357da.png)
![selected-song-from-artist](https://cloud.githubusercontent.com/assets/15209503/23789449/cf7b3702-05b5-11e7-8c1c-75e0fc2bcc6c.png)

**Comment by madasamys** [comment]
We have using split view controller to optimized view for iPhone and iPad. So we could not provide view like attached mockup.

**Comment by michelleashwini** [comment]
1. Select _Aandavar Padaitha Vetriyin Naalithu_ song and scroll to the bottom of the song lyrics
2. Tap on _<_ icon on the navigation bar
3. Tap on another song (_Aananthamae Jeyaa Jeyaa_)
4. The last lyrics items for _Aananthamae Jeyaa Jeyaa_ is displayed
