### ISSUE TITLE
Should not display duplicate song in favourites

### ISSUE THREAD

**Issue by madasamys** [mcruncher/worshipsongs-ios#123]
Unique songs should be displayed in favourites

How to recreate this issue?

1. Go to songs  tab.
2. Long press on song (eg. Aarathanai Aarathanai..)
3. Alert should be displayed
4. Tap on *Yes*
5. Go to *Favourites* tab, the added song should be displayed
6. Repeat step 1 to 5.
7. The duplicate song (eg. Aarathanai Aarathanai..) added

**Comment by VigneshPalanisamy** [comment]
it was expected.

**Comment by madasamys** [comment]
[worship-songs android](https://github.com/mcruncher/worshipsongs-android) should not allow duplication.
