### ISSUE TITLE
Song search does not show the correct lyrics

### ISSUE THREAD

**Issue by melissadarsh** [mcruncher/worshipsongs-ios#233]
Steps to recreate:
1. Search for a song with keyword 'Amazing'
2. Select any song from the list. 
3. Correct lyrics for the song is displayed.
4. Select another song from the search list.
5. Lyrics do not match the selected song.

**Comment by sskjames** [comment]
I can't recreate this problem in v2.8.1.

**Comment by melissadarsh** [comment]
Was unable to recreate the issue in v2.8.1 & 2.8.2 (dev build). Hence, this issue will be closed.
