### ISSUE TITLE
Ability to export Favourite song list as OpenLP service

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-ios#243]
Ref: [WorshipSongs Android Issue 221](https://github.com/mcruncher/worshipsongs-android/issues/221)

**Comment by sskjames** [comment]
[service-file-created-by-app.osj.txt](https://github.com/mcruncher/worshipsongs-ios/files/6225415/service-file-created-by-app.osj.txt)

As of now, this is the JSON created by the app.
I zipped this file with the extension oszl and tried to open it from OpenLP but got the following error:

```
Traceback (most recent call last):
  File "openlp/core/ui/servicemanager.py", line 440, in on_load_service_clicked
  File "openlp/core/ui/servicemanager.py", line 755, in load_file
  File "json/__init__.py", line 265, in load
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 801: ordinal not in range(128)
```

**Comment by sskjames** [comment]
Interestingly, I got the same error when I extracted a oszl file created by OpenLP and re-zipped again with the extension oszl and tried to open it in OpenLP.

**Comment by sskjames** [comment]
Now getting this error:
```
Traceback (most recent call last):
  File "openlp/core/common/openlpmixin.py", line 58, in wrapped
  File "openlp/core/common/openlpmixin.py", line 54, in wrapped
  File "openlp/core/ui/servicemanager.py", line 440, in on_load_service_clicked
  File "openlp/core/common/openlpmixin.py", line 58, in wrapped
  File "openlp/core/common/openlpmixin.py", line 54, in wrapped
  File "openlp/core/ui/servicemanager.py", line 766, in load_file
  File "openlp/core/common/openlpmixin.py", line 58, in wrapped
  File "openlp/core/common/openlpmixin.py", line 54, in wrapped
  File "openlp/core/ui/servicemanager.py", line 825, in process_service_items
  File "openlp/plugins/songs/lib/mediaitem.py", line 555, in service_load
  File "openlp/plugins/songs/lib/openlyricsxml.py", line 371, in xml_to_song
  File "src/lxml/lxml.objectify.pyx", line 1801, in lxml.objectify.fromstring (src/lxml/lxml.objectify.c:25171)
  File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src/lxml/lxml.etree.c:77697)
  File "src/lxml/parser.pxi", line 1819, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:116494)
  File "src/lxml/parser.pxi", line 1700, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:115040)
  File "src/lxml/parser.pxi", line 1040, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:109165)
  File "src/lxml/parser.pxi", line 573, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:103404)
  File "src/lxml/parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:105058)
  File "src/lxml/parser.pxi", line 613, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:103967)
  File "<string>", line None
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1

```

**Comment by sskjames** [comment]
Facing the encoding issue again.
```
Traceback (most recent call last):
  File "openlp/core/ui/servicemanager.py", line 440, in on_load_service_clicked
  File "openlp/core/ui/servicemanager.py", line 755, in load_file
  File "json/__init__.py", line 265, in load
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 1994: ordinal not in range(128)
```
The osj file which I created had the encoding utf-8

**Comment by sskjames** [comment]
Observed the the service file json created by OpenLP 2.4.6 has the encoding "us-ascii" even when Tamil language songs are included.

[service-with-tamil-song.osj.txt](https://github.com/mcruncher/worshipsongs-ios/files/6240327/service-with-tamil-song.osj.txt)

**Comment by sskjames** [comment]
Does OpenLP 2.4.6 support service data files with utf-8 encoding? 
We have a few options:
 - Use "us-ascii" encoding and encode the data in ascii.
 - Check whether the latest version of OpenLP (2.9.x but is not public yet) supports "utf-8" encoding.

**Comment by sskjames** [comment]
Raised this concern as a question in the [OpenLP forum](https://forums.openlp.org/discussion/5502/unable-to-import-service-data-file-with-encoding-utf8)

**Comment by sskjames** [comment]
Installing [OpenLP 2.9.2 aka 3.0 Beta 1](https://openlp.org/blog/2020/12/21/openlp-292-aka-30-beta-1-persistent-peninah.html) to check whether the service files can be opened in it.

**Comment by sskjames** [comment]
Tried to open the service file (created by the app) in OpenLP 2.9.2 and didn't get the encoding error. However, the xml error was still thrown.
Created a service with a Tamil song in OpenLP 2.9.2 and found the encoding to be us-ascii.
Looks like OpenLP expects the service_data json file with the encoding us-ascii.

**Comment by sskjames** [comment]
This info about [non-lossy ascii](https://forums.swift.org/t/what-is-the-default-encoding-of-string-contentsof/38406/2) was helpful.

**Comment by sskjames** [comment]
Now that the json file is encoded in us-ascii, we don't get the encoding error when opening a service file created by the app. However we are getting this error:

    lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1

The reason for this is the xml generated by WorshipSongs adds the attribute `standalone=no`. When I manually removed that attribute and imported again, the file is imported.

**Comment by sskjames** [comment]
Raised an [issue](https://github.com/tadija/AEXML/issues/179) in [AEXML](https://github.com/tadija/AEXML) (which is an excellent lightweight xml library for Swift).
One of the AEXML maintainer responded with a solution to solve this and I managed to get rid of the "standalone" attribute.
After removing this attribute, I managed to import the OpenLP Service File created by WorshipSongs. Thank God!

**Comment by sskjames** [comment]
There are still some glitches that need to be addressed:
 
- a new song is added in OpenLP everytime a service file created by WorshipSongs is imported (is this because of the improper line breaks? Refer screenshot)

![line-breaks](https://user-images.githubusercontent.com/229993/113955019-8c60f400-984d-11eb-8561-a0bbdc4754ab.png)

- unicode characters in topics are not rendered properly

![topics](https://user-images.githubusercontent.com/229993/113955405-3e98bb80-984e-11eb-9f82-af03e63b68cd.png)

**Comment by sskjames** [comment]
The topic information is like this in the service generated by OpenLP:

`
<themes><theme>English {\u0b86\u0b99\u0bcd\u0b95\u0bbf\u0bb2\u0bae\u0bcd}</theme></themes>
`

Here's how it is in the service generated by WorshipSongs:

`
<themes><theme>English {\\u0b86\\u0b99\\u0bcd\\u0b95\\u0bbf\\u0bb2\\u0bae\\u0bcd}<\/theme><\/themes>
`

**Comment by sskjames** [comment]
It's not the xml library that's adding an extra "\" but SwiftyJSON instead when converting to raw string.

**Comment by sskjames** [comment]
Unfortunately SwiftyJSON adds the extra backslashes and I followed a [workaround](https://github.com/SwiftyJSON/SwiftyJSON/issues/440#issuecomment-220689660) and now the topic is resolved correctly. 👍 

However, a new song is added everytime I open a service.

**Comment by sskjames** [comment]
Now the line breaks appear as expected and the final json looks very similar to the one created by OpenLP.
One glitch still remains: A new song is getting added every time a service file generated by WorshipSongs is opened in OpenLP.
So far, I've tested all this in OpenLP 2.9.2. Need to check how things turn out in OpenLP 2.4.6.

**Comment by sskjames** [comment]
OpenLP 2.4.6 managed to load the service file created by WorshipSongs.
Used the latest db from worshipsongs-db-dev.
It had a song with the following details:
- Title: Amazing Grace (my chains are gone)
- Alternate title: unending love, amazing grace
- Authors: Author Unknown {ஆசிரியர் தெரியவில்லை}
- Topics: English {ஆங்கிலம்}

Imported a service file with a song with same title, alternate title, topic but with the author as "John Newton". Observed the following:
- A new song was added with the author as "John Newton".

When the same service was loaded again, another song was imported with the author as "John Newton". Now there were 3 songs with the title "Amazing Grace (my chains are gone)", the one which previously existed in the db and 2 new songs which were added when the service was loaded.

**Comment by sskjames** [comment]
Deleted the newly added songs and changed the author of the song Amazing Grace to "John Newton" and loaded the service again. A new song was still imported.

**Comment by sskjames** [comment]
Had a look at the "service_load" function in https://gitlab.com/openlp/openlp/-/blob/2.4.6/openlp/plugins/songs/lib/mediaitem.py which is called when a service is loaded (Ref: Line no. 829 in https://gitlab.com/openlp/openlp/-/blob/master/openlp/core/ui/servicemanager.py).
```
def service_load(self, item):
        """
        Triggered by a song being loaded by the service manager.
        """
        log.debug('service_load')
        if self.plugin.status != PluginStatus.Active or not item.data_string:
            return
        search_results = self.plugin.manager.get_all_objects(
            Song, Song.search_title == item.data_string['title'], Song.search_title.asc())
        edit_id = 0
        add_song = True
        if search_results:
            for song in search_results:
                if self._authors_match(song, item.data_string['authors']):
                    add_song = False
                    edit_id = song.id
                    break
                # If there's any backing tracks, copy them over.
                if item.background_audio:
                    self._update_background_audio(song, item)
        if add_song and self.add_song_from_service:
            song = self.open_lyrics.xml_to_song(item.xml_version)
            # If there's any backing tracks, copy them over.
            if item.background_audio:
                self._update_background_audio(song, item)
            edit_id = song.id
            self.on_search_text_button_clicked()
        elif add_song and not self.add_song_from_service:
            # Make sure we temporary import formatting tags.
            song = self.open_lyrics.xml_to_song(item.xml_version, True)
            # If there's any backing tracks, copy them over.
            if item.background_audio:
                self._update_background_audio(song, item)
            edit_id = song.id
        # Update service with correct song id and return it to caller.
        item.edit_id = edit_id
        self.generate_footer(item, song)
        return item
```
It's very clear from this that OpenLP adds a new song only when the authors are different.
However, in this case, the problem was because OpenLP couldn't find any song from the db which matches the title in the [header][data][title].

Here is the title in the JSON generated by OpenLP:
`amazing grace my chains are gone @unending love amazing grace`

And this is the title in the JSON generated by the app:
`amazing grace my chains are gone@unending love amazing grace`

There should be a space before the @ which is missing in the JSON generated by the app.

**Comment by sskjames** [comment]
Weird, but for the song God is Good All the time, here is the title in the JSON generated by OpenLP:
`god is good all the time@god is good all the time`
It doesn't have space.

May be is it because the song Amazing Grace has a parenthesis in the title "Amazing Grace (my chains are gone)"?

**Comment by sskjames** [comment]
Tried exporting the song "God is Good all the time" from the app and opened it from OpenLP. This was loaded perfectly. I didn't see new songs created again and again.

**Comment by sskjames** [comment]
Tested with another song "Aruppu Miguthi". This was loaded properly as well. No new songs were created. I observed the problem only in Amazing Grace as the song title has some punctuation characters.

**Comment by sskjames** [comment]
Saw a consistent pattern in OpenLP

Title                           |Alternate Title |Search Title (in db)
-------------------- |---------------|--------------------
Amazing Grace (my chains are gone) | unending love, amazing grace| amazing grace my chains are gone @unending love amazing grace
Bless the Lord (Ten Thousand Reasons) | 10000 Reasons | bless the lord ten thousand reasons @10000 reasons
All Heaven Declares (Forever You Will Be) | Forever You will be | all heaven declares forever you will be @forever you will be
Abide With Me | | abide with me@
Above All Powers | Above all | above all powers@above all

**Comment by sskjames** [comment]
Tested exporting the song Amazing Grace and opened the service in OpenLP. The behaviour is as expected. Thank God!.

**Comment by sskjames** [comment]
Observed some problems in the build uploaded to TestFlight.

**Comment by melissadarsh** [comment]
Performed the steps below for testing: 

1. Added 6 songs into favourites
2. Tapped on the share option and shared as OpenLP Service 
3. Shared the file through email
4. Downloaded the file and opened it in the OpenLP Service desktop app 
5. Observed: Favourite songs appear on the service manager and songs were successfully presented.

Tested on iOS14.4. 

Note: The sharing option should include sharing through airdrop & sharing to the iOS OpenLP app

**Comment by sskjames** [comment]
As part of the refactoring, I introduced another bug which causes only the i18nTitle to be displayed for the songs irrespective of the language they selected. Need to fix this.

**Comment by sskjames** [comment]
As part of the refactoring, I introduced another bug which causes only the i18nTitle to be displayed for the songs irrespective of the language they selected. Need to fix this.

> Performed the steps below during testing:
> 
>     1. Added 6 songs into favourites
> 
>     2. Tapped on the share option and shared as OpenLP Service.
> 
>     3. Shared the file through email.
> 
>     4. Downloaded the file and opened it in the OpenLP Service desktop app.
> 
>     5. Observed: Favourite songs appear on the service manager and songs were successfully presented.
> 
>     6. Repeated the above steps with another favourite list.
> 
>     7. Same is observed.
> 
> 
> Tested on iOS14.4.
> 
> Note: The sharing option should include sharing through airdrop & sharing to the iOS OpenLP app

Thanks @melissadarsh for the testing and feedback. Can we address sharing through airdrop in a separate issue? And I think, the iOS OpenLP app is just a remote to the desktop app.

**Comment by sskjames** [comment]
OpenLP couldn't open the service file created by the app if the favourites has a song without a verse order.
To be specific, in the JSON data, the [serviceitem][data] is not constructed properly if the song does not have a verse order.

**Comment by GermanGospel** [comment]
Exported a oszl via the iOS app (installed via TestFlight today) and tried to open that file in OpenLP 2.4 (Windows):
`Traceback (most recent call last):
  File "openlp\core\ui\servicemanager.py", line 440, in on_load_service_clicked
  File "openlp\core\ui\servicemanager.py", line 766, in load_file
  File "openlp\core\ui\servicemanager.py", line 828, in process_service_items
  File "openlp\core\ui\servicemanager.py", line 1408, in add_service_item
  File "openlp\core\lib\serviceitem.py", line 259, in render
KeyError: 'raw_slide'`

**Comment by sskjames** [comment]
> I exported an oszl file ([favorite_renamed_extension.oszl.zip](https://github.com/mcruncher/worshipsongs-ios/files/6385402/favorite_renamed_extension.oszl.zip), renamed for upload) via the iOS app (installed via TestFlight today) and opened that file in OpenLP 2.4.6 (Windows). I got the following error message, but was able to see the lyrics of both songs afterwards.
> 
> Traceback (most recent call last):
> File "openlp\core\ui\servicemanager.py", line 440, in on_load_service_clicked
> File "openlp\core\ui\servicemanager.py", line 766, in load_file
> File "openlp\core\ui\servicemanager.py", line 828, in process_service_items
> File "openlp\core\ui\servicemanager.py", line 1408, in add_service_item
> File "openlp\core\lib\serviceitem.py", line 259, in render
> KeyError: 'raw_slide'

Hi @GermanGospel, thank you very much for taking time to test this out and report it to us.
I'll look into it.

**Comment by sskjames** [comment]
Hi @GermanGospel, I exported the same songs which you did (Amazing Grace, God of Grace and God of Glory) and I could open it without any issues in OpenLP 2.4.6 (Mac OS 10.15). I'll test this out in Windows as well.

Which build did you use from TestFlight? Is it 3.1.0 (17)?

**Comment by sskjames** [comment]
Hit the problem with OpenLP 2.4.6 (Windows).

**Comment by sskjames** [comment]
I tested this again in Windows and Mac with many different songs but I couldn't recreate the problem.
