### ISSUE TITLE
Search by title should also include songs matching the alternate title

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-ios#254]
### Story
As a user, I want the search results to include songs matching the alternate title of a song when searching by title
So that I can find the songs I want

#### Scenario 1
Given the "Search By Content" option is turned off in Settings
And a song named "Give thanks to the Lord" exists with the alternate title "His love endures"
And the user is in the "Songs" tab
When the user searches by the text "His love endures"
Then the song "Give thanks to the Lord" should be displayed in the search result 

#### Scenario 2
Given the "Search By Content" option is turned off in Settings
And a song named "Anaathi Thaevan Un Adaikkalamae" exists with the alternate title "Anaathi Devan"
And the user is in the "Songs" tab
When the user searches by the text "Deva"
Then the song "Anaathi Thaevan Un Adaikkalamae" should be displayed in the search result

**Comment by melissadarsh** [comment]
Tested v3.1.0 (17) on iOS14.4. Feature works as expected.
